# Generated by Django 5.0.4 on 2024-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Mark1', models.IntegerField()),
                ('mark2', models.IntegerField()),
            ],
        ),
    ]
